name: Trigger auto deployment for app-01

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/app-01-AutoDeployTrigger-0ef8f94e-e37b-4b60-a118-3eac5cc5255a.yml'

  # Allow manual trigger test modified
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APP01_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APP01_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APP01_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: juiceb7597.azurecr.io
          registryUsername: ${{ secrets.APP01_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APP01_REGISTRY_PASSWORD }}
          containerAppName: app-01
          resourceGroup: rg2
          imageToBuild: juiceb7597.azurecr.io/app-01:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


